{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "zkwasm-mini-service.labels" . | nindent 4 }}
type: Opaque
data:
  SERVER_ADMIN_KEY: {{ .Values.secrets.serverAdminKey | b64enc | quote }}
  SETTLER_PRIVATE_ACCOUNT: {{ .Values.secrets.settlerPrivateKey | b64enc | quote }}
{{- end }}
