{{- if .Values.settlementService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkwasm-mini-service.fullname" . }}-settlement
  labels:
    {{- include "zkwasm-mini-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: settlement
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zkwasm-mini-service.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: settlement
{{- end }}
